if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/AsyncBlockSourceTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/AsyncBlockSourceTest[1]_tests.cmake")
else()
  add_test(AsyncBlockSourceTest_NOT_BUILT AsyncBlockSourceTest_NOT_BUILT)
endif()
