if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/NamedSubqueryTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/NamedSubqueryTest[1]_tests.cmake")
else()
  add_test(NamedSubqueryTest_NOT_BUILT NamedSubqueryTest_NOT_BUILT)
endif()
