if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/ParsedQueryTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/ParsedQueryTest[1]_tests.cmake")
else()
  add_test(ParsedQueryTest_NOT_BUILT ParsedQueryTest_NOT_BUILT)
endif()
