if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/PropertyPathTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/PropertyPathTest[1]_tests.cmake")
else()
  add_test(PropertyPathTest_NOT_BUILT PropertyPathTest_NOT_BUILT)
endif()
