if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/QuadTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/QuadTest[1]_tests.cmake")
else()
  add_test(QuadTest_NOT_BUILT QuadTest_NOT_BUILT)
endif()
