if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/SparqlAntlrParserExpressionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/SparqlAntlrParserExpressionTest[1]_tests.cmake")
else()
  add_test(SparqlAntlrParserExpressionTest_NOT_BUILT SparqlAntlrParserExpressionTest_NOT_BUILT)
endif()
