if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/SparqlAntlrParserUpdateTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/SparqlAntlrParserUpdateTest[1]_tests.cmake")
else()
  add_test(SparqlAntlrParserUpdateTest_NOT_BUILT SparqlAntlrParserUpdateTest_NOT_BUILT)
endif()
