if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/UpdateTriplesTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/parser/UpdateTriplesTest[1]_tests.cmake")
else()
  add_test(UpdateTriplesTest_NOT_BUILT UpdateTriplesTest_NOT_BUILT)
endif()
