if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/EncodedIriManagerTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/EncodedIriManagerTest[1]_tests.cmake")
else()
  add_test(EncodedIriManagerTest_NOT_BUILT EncodedIriManagerTest_NOT_BUILT)
endif()
