if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/GraphNameManagerTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/GraphNameManagerTest[1]_tests.cmake")
else()
  add_test(GraphNameManagerTest_NOT_BUILT GraphNameManagerTest_NOT_BUILT)
endif()
