if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/IndexRebuilderTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/IndexRebuilderTest[1]_tests.cmake")
else()
  add_test(IndexRebuilderTest_NOT_BUILT IndexRebuilderTest_NOT_BUILT)
endif()
