if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/KeyOrderTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/KeyOrderTest[1]_tests.cmake")
else()
  add_test(KeyOrderTest_NOT_BUILT KeyOrderTest_NOT_BUILT)
endif()
