if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/ScanSpecificationTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/ScanSpecificationTest[1]_tests.cmake")
else()
  add_test(ScanSpecificationTest_NOT_BUILT ScanSpecificationTest_NOT_BUILT)
endif()
