if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/VocabularyMergerImplTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/VocabularyMergerImplTest[1]_tests.cmake")
else()
  add_test(VocabularyMergerImplTest_NOT_BUILT VocabularyMergerImplTest_NOT_BUILT)
endif()
