if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/SplitVocabularyTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/SplitVocabularyTest[1]_tests.cmake")
else()
  add_test(SplitVocabularyTest_NOT_BUILT SplitVocabularyTest_NOT_BUILT)
endif()
