if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/VocabularyInternalExternalTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/VocabularyInternalExternalTest[1]_tests.cmake")
else()
  add_test(VocabularyInternalExternalTest_NOT_BUILT VocabularyInternalExternalTest_NOT_BUILT)
endif()
