if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/VocabularyInMemoryTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/VocabularyInMemoryTest[1]_tests.cmake")
else()
  add_test(VocabularyInMemoryTest_NOT_BUILT VocabularyInMemoryTest_NOT_BUILT)
endif()
