if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/VocabularyTypesTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/index/vocabulary/VocabularyTypesTest[1]_tests.cmake")
else()
  add_test(VocabularyTypesTest_NOT_BUILT VocabularyTypesTest_NOT_BUILT)
endif()
