if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/AlgorithmBackportTests[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/AlgorithmBackportTests[1]_tests.cmake")
else()
  add_test(AlgorithmBackportTests_NOT_BUILT AlgorithmBackportTests_NOT_BUILT)
endif()
