if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/ConceptsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/ConceptsTest[1]_tests.cmake")
else()
  add_test(ConceptsTest_NOT_BUILT ConceptsTest_NOT_BUILT)
endif()
