if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/FunctionalTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/FunctionalTest[1]_tests.cmake")
else()
  add_test(FunctionalTest_NOT_BUILT FunctionalTest_NOT_BUILT)
endif()
