if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/StartsWithTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/backports/StartsWithTest[1]_tests.cmake")
else()
  add_test(StartsWithTest_NOT_BUILT StartsWithTest_NOT_BUILT)
endif()
