if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/AcceptHeaderTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/AcceptHeaderTest[1]_tests.cmake")
else()
  add_test(AcceptHeaderTest_NOT_BUILT AcceptHeaderTest_NOT_BUILT)
endif()
