if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/AggregateExpressionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/AggregateExpressionTest[1]_tests.cmake")
else()
  add_test(AggregateExpressionTest_NOT_BUILT AggregateExpressionTest_NOT_BUILT)
endif()
