if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/AlignedAllocatorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/AlignedAllocatorTest[1]_tests.cmake")
else()
  add_test(AlignedAllocatorTest_NOT_BUILT AlignedAllocatorTest_NOT_BUILT)
endif()
