if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/AllocatorBackendTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/AllocatorBackendTest[1]_tests.cmake")
else()
  add_test(AllocatorBackendTest_NOT_BUILT AllocatorBackendTest_NOT_BUILT)
endif()
