if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/AllocatorWithLimitTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/AllocatorWithLimitTest[1]_tests.cmake")
else()
  add_test(AllocatorWithLimitTest_NOT_BUILT AllocatorWithLimitTest_NOT_BUILT)
endif()
