if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/BenchmarkMeasurementContainerTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/BenchmarkMeasurementContainerTest[1]_tests.cmake")
else()
  add_test(BenchmarkMeasurementContainerTest_NOT_BUILT BenchmarkMeasurementContainerTest_NOT_BUILT)
endif()
