if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/CachingMemoryResourceTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/CachingMemoryResourceTest[1]_tests.cmake")
else()
  add_test(CachingMemoryResourceTest_NOT_BUILT CachingMemoryResourceTest_NOT_BUILT)
endif()
