if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/CancellationHandleTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/CancellationHandleTest[1]_tests.cmake")
else()
  add_test(CancellationHandleTest_NOT_BUILT CancellationHandleTest_NOT_BUILT)
endif()
