if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/CheckUsePatternTrickTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/CheckUsePatternTrickTest[1]_tests.cmake")
else()
  add_test(CheckUsePatternTrickTest_NOT_BUILT CheckUsePatternTrickTest_NOT_BUILT)
endif()
