if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConfigOptionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConfigOptionTest[1]_tests.cmake")
else()
  add_test(ConfigOptionTest_NOT_BUILT ConfigOptionTest_NOT_BUILT)
endif()
