if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConfigUtilTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConfigUtilTest[1]_tests.cmake")
else()
  add_test(ConfigUtilTest_NOT_BUILT ConfigUtilTest_NOT_BUILT)
endif()
