if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstexprUtilsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstexprUtilsTest[1]_tests.cmake")
else()
  add_test(ConstexprUtilsTest_NOT_BUILT ConstexprUtilsTest_NOT_BUILT)
endif()
