if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstructTripleGeneratorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstructTripleGeneratorTest[1]_tests.cmake")
else()
  add_test(ConstructTripleGeneratorTest_NOT_BUILT ConstructTripleGeneratorTest_NOT_BUILT)
endif()
