if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstructTemplatePreprocessorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstructTemplatePreprocessorTest[1]_tests.cmake")
else()
  add_test(ConstructTemplatePreprocessorTest_NOT_BUILT ConstructTemplatePreprocessorTest_NOT_BUILT)
endif()
