if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstructBatchEvaluatorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ConstructBatchEvaluatorTest[1]_tests.cmake")
else()
  add_test(ConstructBatchEvaluatorTest_NOT_BUILT ConstructBatchEvaluatorTest_NOT_BUILT)
endif()
