if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ContentEncodingHelperTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ContentEncodingHelperTest[1]_tests.cmake")
else()
  add_test(ContentEncodingHelperTest_NOT_BUILT ContentEncodingHelperTest_NOT_BUILT)
endif()
