if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/CryptographicHashUtilsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/CryptographicHashUtilsTest[1]_tests.cmake")
else()
  add_test(CryptographicHashUtilsTest_NOT_BUILT CryptographicHashUtilsTest_NOT_BUILT)
endif()
