if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/CtreHelpersTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/CtreHelpersTest[1]_tests.cmake")
else()
  add_test(CtreHelpersTest_NOT_BUILT CtreHelpersTest_NOT_BUILT)
endif()
