if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/DateYearDurationTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/DateYearDurationTest[1]_tests.cmake")
else()
  add_test(DateYearDurationTest_NOT_BUILT DateYearDurationTest_NOT_BUILT)
endif()
