if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExceptionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExceptionTest[1]_tests.cmake")
else()
  add_test(ExceptionTest_NOT_BUILT ExceptionTest_NOT_BUILT)
endif()
