if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExceptionHandlingTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExceptionHandlingTest[1]_tests.cmake")
else()
  add_test(ExceptionHandlingTest_NOT_BUILT ExceptionHandlingTest_NOT_BUILT)
endif()
