if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExportIdsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExportIdsTest[1]_tests.cmake")
else()
  add_test(ExportIdsTest_NOT_BUILT ExportIdsTest_NOT_BUILT)
endif()
