if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExternalValuesQueryTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ExternalValuesQueryTest[1]_tests.cmake")
else()
  add_test(ExternalValuesQueryTest_NOT_BUILT ExternalValuesQueryTest_NOT_BUILT)
endif()
