if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/FilesystemHelpersTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/FilesystemHelpersTest[1]_tests.cmake")
else()
  add_test(FilesystemHelpersTest_NOT_BUILT FilesystemHelpersTest_NOT_BUILT)
endif()
