if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/FsstCompressorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/FsstCompressorTest[1]_tests.cmake")
else()
  add_test(FsstCompressorTest_NOT_BUILT FsstCompressorTest_NOT_BUILT)
endif()
