if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeneratorsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeneratorsTest[1]_tests.cmake")
else()
  add_test(GeneratorsTest_NOT_BUILT GeneratorsTest_NOT_BUILT)
endif()
