if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/GenericCharTraitsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/GenericCharTraitsTest[1]_tests.cmake")
else()
  add_test(GenericCharTraitsTest_NOT_BUILT GenericCharTraitsTest_NOT_BUILT)
endif()
