if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeoConvertersTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeoConvertersTest[1]_tests.cmake")
else()
  add_test(GeoConvertersTest_NOT_BUILT GeoConvertersTest_NOT_BUILT)
endif()
