if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeoPointTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeoPointTest[1]_tests.cmake")
else()
  add_test(GeoPointTest_NOT_BUILT GeoPointTest_NOT_BUILT)
endif()
