if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeoSparqlHelpersTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/GeoSparqlHelpersTest[1]_tests.cmake")
else()
  add_test(GeoSparqlHelpersTest_NOT_BUILT GeoSparqlHelpersTest_NOT_BUILT)
endif()
