if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/GraphStoreProtocolTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/GraphStoreProtocolTest[1]_tests.cmake")
else()
  add_test(GraphStoreProtocolTest_NOT_BUILT GraphStoreProtocolTest_NOT_BUILT)
endif()
