if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/GroupByTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/GroupByTest[1]_tests.cmake")
else()
  add_test(GroupByTest_NOT_BUILT GroupByTest_NOT_BUILT)
endif()
