if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/HashMapTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/HashMapTest[1]_tests.cmake")
else()
  add_test(HashMapTest_NOT_BUILT HashMapTest_NOT_BUILT)
endif()
