if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/HasPredicateScanTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/HasPredicateScanTest[1]_tests.cmake")
else()
  add_test(HasPredicateScanTest_NOT_BUILT HasPredicateScanTest_NOT_BUILT)
endif()
