if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/IdTableUtilsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/IdTableUtilsTest[1]_tests.cmake")
else()
  add_test(IdTableUtilsTest_NOT_BUILT IdTableUtilsTest_NOT_BUILT)
endif()
