if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/IdTableHelpersTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/IdTableHelpersTest[1]_tests.cmake")
else()
  add_test(IdTableHelpersTest_NOT_BUILT IdTableHelpersTest_NOT_BUILT)
endif()
