if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/IndexTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/IndexTest[1]_tests.cmake")
else()
  add_test(IndexTest_NOT_BUILT IndexTest_NOT_BUILT)
endif()
