if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/InputRangeUtilsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/InputRangeUtilsTest[1]_tests.cmake")
else()
  add_test(InputRangeUtilsTest_NOT_BUILT InputRangeUtilsTest_NOT_BUILT)
endif()
