if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/JsonUtilTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/JsonUtilTest[1]_tests.cmake")
else()
  add_test(JsonUtilTest_NOT_BUILT JsonUtilTest_NOT_BUILT)
endif()
