if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/JThreadTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/JThreadTest[1]_tests.cmake")
else()
  add_test(JThreadTest_NOT_BUILT JThreadTest_NOT_BUILT)
endif()
