if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/KeepPreviousIndexDirsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/KeepPreviousIndexDirsTest[1]_tests.cmake")
else()
  add_test(KeepPreviousIndexDirsTest_NOT_BUILT KeepPreviousIndexDirsTest_NOT_BUILT)
endif()
