if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/LanguageExpressionsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/LanguageExpressionsTest[1]_tests.cmake")
else()
  add_test(LanguageExpressionsTest_NOT_BUILT LanguageExpressionsTest_NOT_BUILT)
endif()
