if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/LazyJsonParserTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/LazyJsonParserTest[1]_tests.cmake")
else()
  add_test(LazyJsonParserTest_NOT_BUILT LazyJsonParserTest_NOT_BUILT)
endif()
