if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/LoadTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/LoadTest[1]_tests.cmake")
else()
  add_test(LoadTest_NOT_BUILT LoadTest_NOT_BUILT)
endif()
