if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/LocatedTriplesTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/LocatedTriplesTest[1]_tests.cmake")
else()
  add_test(LocatedTriplesTest_NOT_BUILT LocatedTriplesTest_NOT_BUILT)
endif()
