if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/LruCacheTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/LruCacheTest[1]_tests.cmake")
else()
  add_test(LruCacheTest_NOT_BUILT LruCacheTest_NOT_BUILT)
endif()
