if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/MetricsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/MetricsTest[1]_tests.cmake")
else()
  add_test(MetricsTest_NOT_BUILT MetricsTest_NOT_BUILT)
endif()
