if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/MinusTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/MinusTest[1]_tests.cmake")
else()
  add_test(MinusTest_NOT_BUILT MinusTest_NOT_BUILT)
endif()
