if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/OnDestructionDontThrowDuringStackUnwindingTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/OnDestructionDontThrowDuringStackUnwindingTest[1]_tests.cmake")
else()
  add_test(OnDestructionDontThrowDuringStackUnwindingTest_NOT_BUILT OnDestructionDontThrowDuringStackUnwindingTest_NOT_BUILT)
endif()
