if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ParametersTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ParametersTest[1]_tests.cmake")
else()
  add_test(ParametersTest_NOT_BUILT ParametersTest_NOT_BUILT)
endif()
