if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ParseExceptionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ParseExceptionTest[1]_tests.cmake")
else()
  add_test(ParseExceptionTest_NOT_BUILT ParseExceptionTest_NOT_BUILT)
endif()
