if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ParseableDurationTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ParseableDurationTest[1]_tests.cmake")
else()
  add_test(ParseableDurationTest_NOT_BUILT ParseableDurationTest_NOT_BUILT)
endif()
