if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/PathSearchTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/PathSearchTest[1]_tests.cmake")
else()
  add_test(PathSearchTest_NOT_BUILT PathSearchTest_NOT_BUILT)
endif()
