if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/PermutationTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/PermutationTest[1]_tests.cmake")
else()
  add_test(PermutationTest_NOT_BUILT PermutationTest_NOT_BUILT)
endif()
