if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/PrefixCompressorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/PrefixCompressorTest[1]_tests.cmake")
else()
  add_test(PrefixCompressorTest_NOT_BUILT PrefixCompressorTest_NOT_BUILT)
endif()
