if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/QueryEventLogTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/QueryEventLogTest[1]_tests.cmake")
else()
  add_test(QueryEventLogTest_NOT_BUILT QueryEventLogTest_NOT_BUILT)
endif()
