if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/QueryPlannerSpatialJoinTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/QueryPlannerSpatialJoinTest[1]_tests.cmake")
else()
  add_test(QueryPlannerSpatialJoinTest_NOT_BUILT QueryPlannerSpatialJoinTest_NOT_BUILT)
endif()
