if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/RandomExpressionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/RandomExpressionTest[1]_tests.cmake")
else()
  add_test(RandomExpressionTest_NOT_BUILT RandomExpressionTest_NOT_BUILT)
endif()
