if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/RebuildIndexStrategyTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/RebuildIndexStrategyTest[1]_tests.cmake")
else()
  add_test(RebuildIndexStrategyTest_NOT_BUILT RebuildIndexStrategyTest_NOT_BUILT)
endif()
