if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/RelationalExpressionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/RelationalExpressionTest[1]_tests.cmake")
else()
  add_test(RelationalExpressionTest_NOT_BUILT RelationalExpressionTest_NOT_BUILT)
endif()
