if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ResourceMonitorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ResourceMonitorTest[1]_tests.cmake")
else()
  add_test(ResourceMonitorTest_NOT_BUILT ResourceMonitorTest_NOT_BUILT)
endif()
