if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ResultTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ResultTest[1]_tests.cmake")
else()
  add_test(ResultTest_NOT_BUILT ResultTest_NOT_BUILT)
endif()
