if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/RuntimeParametersTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/RuntimeParametersTest[1]_tests.cmake")
else()
  add_test(RuntimeParametersTest_NOT_BUILT RuntimeParametersTest_NOT_BUILT)
endif()
