if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/RuntimeInformationTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/RuntimeInformationTest[1]_tests.cmake")
else()
  add_test(RuntimeInformationTest_NOT_BUILT RuntimeInformationTest_NOT_BUILT)
endif()
