if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/SelectClauseTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/SelectClauseTest[1]_tests.cmake")
else()
  add_test(SelectClauseTest_NOT_BUILT SelectClauseTest_NOT_BUILT)
endif()
