if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/SerializerTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/SerializerTest[1]_tests.cmake")
else()
  add_test(SerializerTest_NOT_BUILT SerializerTest_NOT_BUILT)
endif()
