if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ServiceTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ServiceTest[1]_tests.cmake")
else()
  add_test(ServiceTest_NOT_BUILT ServiceTest_NOT_BUILT)
endif()
