if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/SortedSequenceTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/SortedSequenceTest[1]_tests.cmake")
else()
  add_test(SortedSequenceTest_NOT_BUILT SortedSequenceTest_NOT_BUILT)
endif()
