if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/SparqlExpressionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/SparqlExpressionTest[1]_tests.cmake")
else()
  add_test(SparqlExpressionTest_NOT_BUILT SparqlExpressionTest_NOT_BUILT)
endif()
