if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/SparqlExpressionMemberFunctionsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/SparqlExpressionMemberFunctionsTest[1]_tests.cmake")
else()
  add_test(SparqlExpressionMemberFunctionsTest_NOT_BUILT SparqlExpressionMemberFunctionsTest_NOT_BUILT)
endif()
