if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/SparqlExpressionGeneratorsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/SparqlExpressionGeneratorsTest[1]_tests.cmake")
else()
  add_test(SparqlExpressionGeneratorsTest_NOT_BUILT SparqlExpressionGeneratorsTest_NOT_BUILT)
endif()
