if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/StringBatcherTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/StringBatcherTest[1]_tests.cmake")
else()
  add_test(StringBatcherTest_NOT_BUILT StringBatcherTest_NOT_BUILT)
endif()
