if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/StringSortComparatorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/StringSortComparatorTest[1]_tests.cmake")
else()
  add_test(StringSortComparatorTest_NOT_BUILT StringSortComparatorTest_NOT_BUILT)
endif()
