if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/StringPairHashMapTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/StringPairHashMapTest[1]_tests.cmake")
else()
  add_test(StringPairHashMapTest_NOT_BUILT StringPairHashMapTest_NOT_BUILT)
endif()
