if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/TakeUntilInclusiveViewTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/TakeUntilInclusiveViewTest[1]_tests.cmake")
else()
  add_test(TakeUntilInclusiveViewTest_NOT_BUILT TakeUntilInclusiveViewTest_NOT_BUILT)
endif()
