if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/TaskQueueTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/TaskQueueTest[1]_tests.cmake")
else()
  add_test(TaskQueueTest_NOT_BUILT TaskQueueTest_NOT_BUILT)
endif()
