if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/TokenTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/TokenTest[1]_tests.cmake")
else()
  add_test(TokenTest_NOT_BUILT TokenTest_NOT_BUILT)
endif()
