if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/TransparentFunctorsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/TransparentFunctorsTest[1]_tests.cmake")
else()
  add_test(TransparentFunctorsTest_NOT_BUILT TransparentFunctorsTest_NOT_BUILT)
endif()
