if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/UnionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/UnionTest[1]_tests.cmake")
else()
  add_test(UnionTest_NOT_BUILT UnionTest_NOT_BUILT)
endif()
