if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/UniqueCleanupTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/UniqueCleanupTest[1]_tests.cmake")
else()
  add_test(UniqueCleanupTest_NOT_BUILT UniqueCleanupTest_NOT_BUILT)
endif()
