if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/UnitOfMeasurementTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/UnitOfMeasurementTest[1]_tests.cmake")
else()
  add_test(UnitOfMeasurementTest_NOT_BUILT UnitOfMeasurementTest_NOT_BUILT)
endif()
