if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/UpdateFetcherTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/UpdateFetcherTest[1]_tests.cmake")
else()
  add_test(UpdateFetcherTest_NOT_BUILT UpdateFetcherTest_NOT_BUILT)
endif()
