if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/UriParserUriTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/UriParserUriTest[1]_tests.cmake")
else()
  add_test(UriParserUriTest_NOT_BUILT UriParserUriTest_NOT_BUILT)
endif()
