if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/UrlParserTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/UrlParserTest[1]_tests.cmake")
else()
  add_test(UrlParserTest_NOT_BUILT UrlParserTest_NOT_BUILT)
endif()
