if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ValidatorTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ValidatorTest[1]_tests.cmake")
else()
  add_test(ValidatorTest_NOT_BUILT ValidatorTest_NOT_BUILT)
endif()
