if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ValueIdComparatorsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ValueIdComparatorsTest[1]_tests.cmake")
else()
  add_test(ValueIdComparatorsTest_NOT_BUILT ValueIdComparatorsTest_NOT_BUILT)
endif()
