if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ValuesForTestingTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ValuesForTestingTest[1]_tests.cmake")
else()
  add_test(ValuesForTestingTest_NOT_BUILT ValuesForTestingTest_NOT_BUILT)
endif()
