if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/VariableToColumnMapTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/VariableToColumnMapTest[1]_tests.cmake")
else()
  add_test(VariableToColumnMapTest_NOT_BUILT VariableToColumnMapTest_NOT_BUILT)
endif()
