if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/VariantRangeFilterTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/VariantRangeFilterTest[1]_tests.cmake")
else()
  add_test(VariantRangeFilterTest_NOT_BUILT VariantRangeFilterTest_NOT_BUILT)
endif()
