if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/VectorWithMemoryLimitTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/VectorWithMemoryLimitTest[1]_tests.cmake")
else()
  add_test(VectorWithMemoryLimitTest_NOT_BUILT VectorWithMemoryLimitTest_NOT_BUILT)
endif()
