if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/ViewsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/ViewsTest[1]_tests.cmake")
else()
  add_test(ViewsTest_NOT_BUILT ViewsTest_NOT_BUILT)
endif()
