if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/WordsAndDocsFileParserTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/WordsAndDocsFileParserTest[1]_tests.cmake")
else()
  add_test(WordsAndDocsFileParserTest_NOT_BUILT WordsAndDocsFileParserTest_NOT_BUILT)
endif()
