if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/CountConnectedSubgraphsTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/CountConnectedSubgraphsTest[1]_tests.cmake")
else()
  add_test(CountConnectedSubgraphsTest_NOT_BUILT CountConnectedSubgraphsTest_NOT_BUILT)
endif()
