if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/ExistsJoinTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/ExistsJoinTest[1]_tests.cmake")
else()
  add_test(ExistsJoinTest_NOT_BUILT ExistsJoinTest_NOT_BUILT)
endif()
