if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/GroupConcatExpressionTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/GroupConcatExpressionTest[1]_tests.cmake")
else()
  add_test(GroupConcatExpressionTest_NOT_BUILT GroupConcatExpressionTest_NOT_BUILT)
endif()
