if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/GroupByHashMapOptimizationTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/GroupByHashMapOptimizationTest[1]_tests.cmake")
else()
  add_test(GroupByHashMapOptimizationTest_NOT_BUILT GroupByHashMapOptimizationTest_NOT_BUILT)
endif()
