if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/IndexScanTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/IndexScanTest[1]_tests.cmake")
else()
  add_test(IndexScanTest_NOT_BUILT IndexScanTest_NOT_BUILT)
endif()
