if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/NamedResultCacheTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/NamedResultCacheTest[1]_tests.cmake")
else()
  add_test(NamedResultCacheTest_NOT_BUILT NamedResultCacheTest_NOT_BUILT)
endif()
