if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/QueryExecutionTreeTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/QueryExecutionTreeTest[1]_tests.cmake")
else()
  add_test(QueryExecutionTreeTest_NOT_BUILT QueryExecutionTreeTest_NOT_BUILT)
endif()
