if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/ResponseJsonTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/ResponseJsonTest[1]_tests.cmake")
else()
  add_test(ResponseJsonTest_NOT_BUILT ResponseJsonTest_NOT_BUILT)
endif()
