if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/SpatialJoinCachedIndexTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/SpatialJoinCachedIndexTest[1]_tests.cmake")
else()
  add_test(SpatialJoinCachedIndexTest_NOT_BUILT SpatialJoinCachedIndexTest_NOT_BUILT)
endif()
