if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/StringMappingTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/StringMappingTest[1]_tests.cmake")
else()
  add_test(StringMappingTest_NOT_BUILT StringMappingTest_NOT_BUILT)
endif()
