if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/TextIndexScanForWordTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/engine/TextIndexScanForWordTest[1]_tests.cmake")
else()
  add_test(TextIndexScanForWordTest_NOT_BUILT TextIndexScanForWordTest_NOT_BUILT)
endif()
