if(EXISTS "/home/userNoPriv/code/qlever/qlever-code/build-review/test/rdfTypes/VariableTest[1]_tests.cmake")
  include("/home/userNoPriv/code/qlever/qlever-code/build-review/test/rdfTypes/VariableTest[1]_tests.cmake")
else()
  add_test(VariableTest_NOT_BUILT VariableTest_NOT_BUILT)
endif()
